### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by ondrejspilkaABB** [globalsign/est#22]
Ubuntu 18.04 on WSL clean install
```
$go get github.com/globalsign/est
# github.com/go-chi/chi
go/src/github.com/go-chi/chi/tree.go:60:20: invalid operation: 2 << n (shift count type int, must be unsigned integer)
# github.com/google/go-tpm/tpm2
go/src/github.com/google/go-tpm/tpm2/open_other.go:38:6: undefined: errors.Is
```
![image](https://user-images.githubusercontent.com/69234713/131849701-a1162971-6ebb-4b09-b441-6bc3fa038160.png)

**Comment by paulgriffiths** [comment]
@ondrejspilkaABB : which version of Go are you using?

**Comment by ondrejspilkaABB** [comment]
go version go1.10.4 linux/amd64

Od: Paul Griffiths ***@***.***>
Odesláno: Thursday, September 2, 2021 3:25 PM
Komu: globalsign/est ***@***.***>
Kopie: Ondrej Spilka ***@***.***>; Mention ***@***.***>
Předmět: Re: [globalsign/est] Install fails (#22)

This email originated from outside of your organization. Please do not click on links or open attachments unless you recognize the sender and know the content is safe.


@ondrejspilkaABB<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FondrejspilkaABB&data=04%7C01%7Condrej.spilka%40cz.abb.com%7C9437af26f6b44a4d432308d96e151b8b%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637661859199740931%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QAMNRsQ0b2XS3vUZvE%2FM%2FOwAUC9gwAr02VZ%2BsiLK5M4%3D&reserved=0> : which version of Go are you using?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fglobalsign%2Fest%2Fissues%2F22%23issuecomment-911680313&data=04%7C01%7Condrej.spilka%40cz.abb.com%7C9437af26f6b44a4d432308d96e151b8b%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637661859199750884%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zfVSYVcH9ilGAdrxKzMDBXU0aRlTikemwGcRWvDxCfI%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQQHAGIE4JEXC4GNIYP3XNDT753L3ANCNFSM5DJCUZMQ&data=04%7C01%7Condrej.spilka%40cz.abb.com%7C9437af26f6b44a4d432308d96e151b8b%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637661859199750884%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xe2qRMD1yE4tLOnKTXubI9hDS2HKNMI9eUASOc6Z3Rw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Condrej.spilka%40cz.abb.com%7C9437af26f6b44a4d432308d96e151b8b%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637661859199760848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MAFiLufXzUoykFXERtTWWXFAMeitYVND9kYSnd3v4UU%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Condrej.spilka%40cz.abb.com%7C9437af26f6b44a4d432308d96e151b8b%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637661859199760848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9DXsDz%2Bl2UoJpnewJi4GBxfC66kDF8gI3a4uABJ5kio%3D&reserved=0>.

**Comment by paulgriffiths** [comment]
> go version go1.10.4

This package supports a minimum Go version of 1.13, so upgrading to a more recent version of Go is the only real solution (version 1.17 is the current one). Most fundamentally, the package and all its dependencies use Go modules, which weren't introduced until version 1.11, and specifically the error-handling functionality referred to in your second error message was introduced in version 1.13.

**Comment by ondrejspilkaABB** [comment]
Thanks, my fault, didn't expect to have outdated Go version.
