### ISSUE TITLE
Installation guide is deprecated

### ISSUE THREAD

**Issue by brokoler** [globalsign/est#24]
Hello,

my system is running the latest go version go1.18.2 linux/amd64

With this version, the mentioned install guide is deprecated since following error is shown:
![grafik](https://user-images.githubusercontent.com/57031979/169298172-3794cd67-724d-4502-b14c-c774024a3e41.png)

Following commands are working instead:
`go install github.com/globalsign/est/cmd/estserver@latest`
`go install github.com/globalsign/est/cmd/estclient@latest`

**Comment by toddgaunt-gs** [comment]
Hello @brokoler, I'll take a look at updating the installation guide soon.
